// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBKEovyKrrHwYuKm10gj0NI5Y6MPco2cY',
    appId: '1:663472703976:web:e392b4aa7542e29ff4bc5d',
    messagingSenderId: '663472703976',
    projectId: 'final-exam-fb-631f4',
    authDomain: 'final-exam-fb-631f4.firebaseapp.com',
    storageBucket: 'final-exam-fb-631f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfIfIKPJURkCpBE0d2ByAnsC4sDVVSt0g',
    appId: '1:663472703976:android:4d18e98ed1dfcefaf4bc5d',
    messagingSenderId: '663472703976',
    projectId: 'final-exam-fb-631f4',
    storageBucket: 'final-exam-fb-631f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZjNJPfNZD4zX_NyTwsP60ewkMf40sMI',
    appId: '1:663472703976:ios:5b9d6369327ff662f4bc5d',
    messagingSenderId: '663472703976',
    projectId: 'final-exam-fb-631f4',
    storageBucket: 'final-exam-fb-631f4.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ZjNJPfNZD4zX_NyTwsP60ewkMf40sMI',
    appId: '1:663472703976:ios:5a1fde0e3626db7df4bc5d',
    messagingSenderId: '663472703976',
    projectId: 'final-exam-fb-631f4',
    storageBucket: 'final-exam-fb-631f4.appspot.com',
    iosBundleId: 'com.example.finalExam.RunnerTests',
  );
}
