name: assignment2
description: A new Flutter project.
<<<<<<< Updated upstream
=======
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
>>>>>>> Stashed changes

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

<<<<<<< Updated upstream
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.1.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
=======
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.1.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  riverpod: ^2.4.6
  flutter_riverpod: ^2.4.6
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:
<<<<<<< Updated upstream
=======
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
>>>>>>> Stashed changes
  uses-material-design: true

  assets:
    # - assets/asset1.jpg
    # - assets/asset2.jpg
    # - assets/asset3.jpg
    - assets/asset1-removebg-preview.png
    - assets/asset2-removebg-preview.png
<<<<<<< Updated upstream
=======

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
>>>>>>> Stashed changes
